/*
 * Copyright (C) 2014 Chenko
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package lvpd.tool;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author Sergey
 */
public class MainGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        betaDialogCloseButton = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        statsDialogResetButton = new javax.swing.JButton();
        statsLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        statsDialogCloseButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        arrestTab = new javax.swing.JPanel();
        vehicleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lightLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox23 = new javax.swing.JCheckBox();
        weaponsComboBox = new javax.swing.JComboBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        drugsComboBox = new javax.swing.JComboBox();
        drugsTextField = new javax.swing.JTextField();
        jCheckBox29 = new javax.swing.JCheckBox();
        materialsTextField = new javax.swing.JTextField();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        materialsTraffick = new javax.swing.JRadioButton();
        firearmsTraffick = new javax.swing.JRadioButton();
        drugsTraffick = new javax.swing.JRadioButton();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        dischargeComboBox = new javax.swing.JComboBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        heavyLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox43 = new javax.swing.JCheckBox();
        kidnappingLEO = new javax.swing.JRadioButton();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        assaultandbatteryLEO = new javax.swing.JRadioButton();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        successfulLEO = new javax.swing.JRadioButton();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        playeridSpinner = new javax.swing.JSpinner();
        calculateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        copytoclipboardButton = new javax.swing.JButton();
        attemptedLEO = new javax.swing.JRadioButton();
        assaultLEO = new javax.swing.JRadioButton();
        assaultdeadlyLEO = new javax.swing.JRadioButton();
        resetButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        offenderName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ticketTab = new javax.swing.JPanel();
        impoundTab = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jDialog1.setTitle("Unavailable");
        jDialog1.setIconImage(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Logo32.png")));
        jDialog1.setLocationByPlatform(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(335, 360));
        jDialog1.setType(java.awt.Window.Type.POPUP);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); 
        jDialog1.setLocation(dim.width/2-jDialog1.getSize().width/2, dim.height/2-jDialog1.getSize().height/2);

        jLabel3.setText("<html><b><font size=5><font color=\"red\">This feature is currently unavailable</font></b><br><hr><br>The LVPD Tool in Java is currently in beta and as such certain functions are unavailable for any of the following reasons: <br><br>-Not started yet <br>-Incomplete<br>-Bugged to hell<br><br><b>Please be patient during the development process and report any bugs to <u>Chenko!!</u><br><br><hr><br></html>");

        betaDialogCloseButton.setText("Close");
        betaDialogCloseButton.setAlignmentX(0.5F);
        betaDialogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaDialogCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(betaDialogCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(betaDialogCloseButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setTitle("Stats");
        jDialog2.setMinimumSize(new java.awt.Dimension(240, 240));
        jDialog2.setResizable(false);
        jDialog2.setLocation(dim.width/2-jDialog2.getSize().width/2, dim.height/2-jDialog2.getSize().height/2);

        statsDialogResetButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statsDialogResetButton.setText("<html><font color=red>Reset Stats");
        statsDialogResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsDialogResetButtonActionPerformed(evt);
            }
        });

        statsLabel.setText("<html><b>Arrests:</b> <br><b>Time:</b> <br><b>Fines:</b> <br><b>Strikes:</b> ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Lifetime Stats");

        statsDialogCloseButton.setText("Close");
        statsDialogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsDialogCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(statsDialogCloseButton)
                                .addComponent(statsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(statsDialogResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(statsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statsDialogCloseButton)
                .addGap(18, 18, 18)
                .addComponent(statsDialogResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LVPD Tool v2");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Logo32.png")));
        setName("mainFrame"); // NOI18N

        jScrollPane2.setPreferredSize(new java.awt.Dimension(900, 920));

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(900, 920));
        jTabbedPane1.setBounds(0, 0, dim.width, dim.height);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        arrestTab.setAutoscrolls(true);
        arrestTab.setPreferredSize(new java.awt.Dimension(854, 890));

        vehicleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vehicleLabel.setText("Vehicular Offences");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lightLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lightLabel.setText("Light Offenses");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jCheckBox1.setText("Illegal Parking");
        jCheckBox1.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox1.getText()));

        jCheckBox2.setText("Failure to Provide Valid Registration");
        jCheckBox2.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox2.getText()));

        jCheckBox3.setText("Illegal Shortcut");
        jCheckBox3.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox3.getText()));

        jCheckBox4.setText("Unlawful Hydraulics");
        jCheckBox4.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox4.getText()));

        jCheckBox5.setText("Unlawful Nos");
        jCheckBox5.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox5.getText()));

        jCheckBox6.setText("Reckless Driving");
        jCheckBox6.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox6.getText()));

        jCheckBox7.setText("Reckless Endangerment");
        jCheckBox7.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox7.getText()));

        jCheckBox8.setText("Street Racing");
        jCheckBox8.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox8.getText()));

        jCheckBox9.setText("Driving without due care and attention");
        jCheckBox9.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox9.getText()));

        jCheckBox10.setText("Verbal Assault");
        jCheckBox10.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox10.getText()));

        jCheckBox11.setText("Loitering on Govt Property");
        jCheckBox11.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox11.getText()));

        jCheckBox12.setText("Trespassing");
        jCheckBox12.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox12.getText()));

        jCheckBox13.setText("Indecent Exposure");
        jCheckBox13.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox13.getText()));

        jCheckBox14.setText("Lewd Gesture");
        jCheckBox14.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox14.getText()));

        jCheckBox15.setText("Vandalism");
        jCheckBox15.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox15.getText()));

        jCheckBox16.setText("Affray");
        jCheckBox16.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox16.getText()));

        jCheckBox17.setText("Misuse of 911");
        jCheckBox17.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox17.getText()));

        jCheckBox18.setText("Failure to Provide ID");
        jCheckBox18.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox18.getText()));

        jCheckBox20.setText("Resisting Arrest");
        jCheckBox20.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox20.getText()));

        jCheckBox21.setText("Evading Arrest");
        jCheckBox21.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox21.getText()));

        jCheckBox22.setText("Disorderly Conduct");
        jCheckBox22.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox22.getText()));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Medium Offenses");

        jCheckBox23.setText("Unlawful Possession of a Firearm");
        jCheckBox23.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox23.getText()));

        weaponsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Katana/Brass Knuckles", "Silenced", "Deagle", "Low Caliber", "High Caliber" }));

        jCheckBox24.setText("Vehicular Assault");
        jCheckBox24.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox24.getText()));

        jCheckBox25.setText("(Attempted) GTA");
        jCheckBox25.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox25.getText()));

        jCheckBox26.setText("(Successful) GTA");
        jCheckBox26.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox26.getText()));

        jCheckBox27.setText("DUI");
        jCheckBox27.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox27.getText()));

        jCheckBox28.setText("Possession of Narcotics");
        jCheckBox28.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox28.getText()));

        drugsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cocaine", "Pot", "Speed" }));

        drugsTextField.setText("0");

        jCheckBox29.setText("Possession of Materials");
        jCheckBox29.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox29.getText()));

        materialsTextField.setText("0");

        jCheckBox30.setText("Impersonating a LEO");
        jCheckBox30.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox30.getText()));

        jCheckBox31.setText("Obstruction of Justice");
        jCheckBox31.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox31.getText()));

        jCheckBox32.setText("Conspiracy to Commit Murder");
        jCheckBox32.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox32.getText()));

        jCheckBox33.setText("Aiding and Abetting");
        jCheckBox33.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox33.getText()));

        jCheckBox34.setText("Hit and Run");
        jCheckBox34.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox34.getText()));

        jCheckBox35.setText("Trafficking");
        jCheckBox35.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox35.getText()));

        materialsTraffick.setText("Materials");
        materialsTraffick.setToolTipText("<html><b>Trafficking Illegal Materials </b><br>Fine: $5000<br>Time: 15 minutes<br>Strikes: 0 </html>");

        firearmsTraffick.setText("Firearms");
        firearmsTraffick.setToolTipText("<html><b>Trafficking Illegal Firearms </b><br>Fine: $5000<br>Time: 20 minutes<br>Strikes: 0 </html>");

        drugsTraffick.setText("Narcotics");
        drugsTraffick.setToolTipText("<html><b>Trafficking Illegal Narcotics </b><br>Fine: $5000<br>Time: 15 minutes<br>Strikes: 0 </html>");

        jCheckBox37.setText("Harassment");
        jCheckBox37.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox37.getText()));

        jCheckBox38.setText("Unlawful Discharge of Firearm");
        jCheckBox38.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox38.getText()));

        dischargeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Multiple/Rapid" }));

        jCheckBox39.setText("Public Endangerment");
        jCheckBox39.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox39.getText()));

        jCheckBox40.setText("Fraud");
        jCheckBox40.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox40.getText()));

        jCheckBox41.setText("Lying to a LEO");
        jCheckBox41.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox41.getText()));

        jCheckBox42.setText("Driving whilst suspended");
        jCheckBox42.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox42.getText()));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        heavyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heavyLabel.setText("Heavy Offenses");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jCheckBox43.setText("Attempted Murder");
        jCheckBox43.setToolTipText("<html><b>Attempted Murder </b><br>Fine: $10000<br>Time: 30 minutes<br>Strikes: 0 </html>");

        kidnappingLEO.setText("<html><i>of LEO</i></html>");
        kidnappingLEO.setToolTipText("<html><b>Kidnapping of LEO</b><br>Fine: $25000<br>Time: 50 minutes<br>Strikes: 0 </html>");

        jCheckBox44.setText("Instigating Public Anarchy");
        jCheckBox44.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox44.getText()));

        jCheckBox45.setText("Racketeering");
        jCheckBox45.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox45.getText()));

        jCheckBox46.setText("Kidnapping");
        jCheckBox46.setToolTipText("<html><b>Kidnapping </b><br>Fine: $10000<br>Time: 30 minutes<br>Strikes: 0 </html>");

        assaultandbatteryLEO.setText("<html><i>of LEO</i></html>");
        assaultandbatteryLEO.setToolTipText("<html><b>Assault and Battery of LEO</b><br>Fine: $6000<br>Time: 25 minutes<br>Strikes: 0 </html>");

        jCheckBox47.setText("Robbery");
        jCheckBox47.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox47.getText()));

        jCheckBox48.setText("Armed Robbery");
        jCheckBox48.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox48.getText()));

        jCheckBox50.setText("Illegal Gambling");
        jCheckBox50.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox50.getText()));

        jCheckBox51.setText("Bribery");
        jCheckBox51.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox51.getText()));

        jCheckBox52.setText("Assault");
        jCheckBox52.setToolTipText("<html><b>Assault </b><br>Fine: $2000<br>Time: 15 minutes<br>Strikes: 0 </html>");

        jCheckBox53.setText("Assault and Battery");
        jCheckBox53.setToolTipText("<html><b>Assault and Battery</b><br>Fine: $2500<br>Time: 20 minutes<br>Strikes: 0 </html>");

        jCheckBox54.setText("Assault with a deadly weapon");
        jCheckBox54.setToolTipText("<html><b>Assault with a deadly weapon</b><br>Fine: $5000<br>Time: 20 minutes<br>Strikes: 0 </html>");

        jCheckBox55.setText("Extortion");
        jCheckBox55.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox55.getText()));

        jCheckBox56.setText("Scamming");
        jCheckBox56.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox56.getText()));

        jCheckBox57.setText("Arson");
        jCheckBox57.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox57.getText()));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Capital Offenses");

        jCheckBox58.setText("Domestic Terrorism");
        jCheckBox58.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox58.getText()));

        jCheckBox59.setText("Successful Murder");
        jCheckBox59.setToolTipText("<html><b>Successful Murder</b><br>Fine: $20000<br>Time: 45 minutes<br>Strikes: 0 </html>");

        jCheckBox60.setText("Mass Murder");
        jCheckBox60.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox60.getText()));

        successfulLEO.setText("<html><i>of LEO</i></html>");
        successfulLEO.setToolTipText("<html><b>Successful Murderof LEO</b><br>Fine: $25000<br>Time: 50 minutes<br>Strikes: 0 </html>");

        jCheckBox61.setText("Police Corruption");
        jCheckBox61.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox61.getText()));

        jCheckBox62.setText("Piracy (Sea)");
        jCheckBox62.setToolTipText(CrimesSource.getCrimeTooltip(jCheckBox62.getText()));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("<html><b>Select the playerid here");

        calculateButton.setText("<html><b><font color = \"blue\">Calculate");
        calculateButton.setActionCommand("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("<html><b>Fine:</b> $0<br><br><b>Time: </b>0 minutes<br><br><b>Strikes: </b>0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Results");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Command:");

        copytoclipboardButton.setText("Copy to Clipboard");
        copytoclipboardButton.setActionCommand("Copy");
        copytoclipboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copytoclipboardButtonActionPerformed(evt);
            }
        });

        attemptedLEO.setText("<html><i>of LEO</i></html>");
        attemptedLEO.setToolTipText("<html><b>Attempted Murder of LEO</b><br>Fine: $15000<br>Time: 50 minutes<br>Strikes: 0 </html>");

        assaultLEO.setText("<html><i>of LEO</i></html>");
        assaultLEO.setToolTipText("<html><b>Assault of LEO</b><br>Fine: $2500<br>Time: 20 minutes<br>Strikes: 0 </html>");

        assaultdeadlyLEO.setText("<html><i>of LEO</i></html>");
        assaultdeadlyLEO.setToolTipText("<html><b>Assault with a deadly weapon of LEO</b><br>Fine: $6000<br>Time: 25 minutes<br>Strikes: 0 </html>");

        resetButton.setText("<html><b>Reset");
        resetButton.setActionCommand("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Create Criminal Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        jLabel8.setText("<html><b>Criminal Name (No underscore): ");

        javax.swing.GroupLayout arrestTabLayout = new javax.swing.GroupLayout(arrestTab);
        arrestTab.setLayout(arrestTabLayout);
        arrestTabLayout.setHorizontalGroup(
            arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrestTabLayout.createSequentialGroup()
                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arrestTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox43)
                                    .addComponent(heavyLabel)
                                    .addComponent(jCheckBox44)
                                    .addComponent(jCheckBox45)
                                    .addComponent(jCheckBox46)
                                    .addComponent(jCheckBox47)
                                    .addComponent(jCheckBox48)
                                    .addComponent(jCheckBox50)
                                    .addComponent(jCheckBox51)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kidnappingLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(attemptedLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox52)
                                    .addComponent(jCheckBox53)
                                    .addComponent(jCheckBox54)
                                    .addComponent(jCheckBox55)
                                    .addComponent(jCheckBox56)
                                    .addComponent(jCheckBox57)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(assaultandbatteryLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(assaultLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(assaultdeadlyLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(49, 49, 49)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jCheckBox58)
                                    .addComponent(jCheckBox59)
                                    .addComponent(jCheckBox60)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(successfulLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox61)
                                    .addComponent(jCheckBox62))
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arrestTabLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arrestTabLayout.createSequentialGroup()
                                                        .addComponent(copytoclipboardButton)
                                                        .addGap(15, 15, 15))
                                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButton2))
                                                        .addGap(5, 5, 5))))
                                            .addGroup(arrestTabLayout.createSequentialGroup()
                                                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(arrestTabLayout.createSequentialGroup()
                                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)))
                                        .addGap(16, 16, 16)
                                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(playeridSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(offenderName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(arrestTabLayout.createSequentialGroup()
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(vehicleLabel)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arrestTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox1))))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox16)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox20)
                            .addComponent(jCheckBox21)
                            .addComponent(jCheckBox22))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox23)
                            .addComponent(jCheckBox24)
                            .addComponent(jCheckBox25)
                            .addComponent(jCheckBox26)
                            .addComponent(jCheckBox27)
                            .addComponent(jCheckBox28)
                            .addComponent(jCheckBox29)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(weaponsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addComponent(drugsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(drugsTextField))
                                    .addComponent(materialsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCheckBox30)
                            .addComponent(jCheckBox31)
                            .addComponent(jCheckBox32))
                        .addGap(20, 20, 20)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox33)
                                    .addComponent(jCheckBox34)
                                    .addComponent(jCheckBox35)
                                    .addComponent(jCheckBox37)
                                    .addComponent(jCheckBox38)
                                    .addComponent(jCheckBox39)
                                    .addComponent(jCheckBox40)
                                    .addComponent(jCheckBox41)
                                    .addComponent(jCheckBox42)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firearmsTraffick)
                                            .addComponent(drugsTraffick)
                                            .addComponent(materialsTraffick))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE))
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(dischargeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        arrestTabLayout.setVerticalGroup(
            arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrestTabLayout.createSequentialGroup()
                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arrestTabLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jCheckBox33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(materialsTraffick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firearmsTraffick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drugsTraffick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dischargeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox42))
                    .addGroup(arrestTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weaponsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(drugsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(materialsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox32))
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox9))
                                    .addGroup(arrestTabLayout.createSequentialGroup()
                                        .addComponent(jCheckBox10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox22))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arrestTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(successfulLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox62))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(arrestTabLayout.createSequentialGroup()
                                    .addComponent(heavyLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox43)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(attemptedLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox44)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox45)
                                    .addGap(6, 6, 6)
                                    .addComponent(jCheckBox46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(kidnappingLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox48)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox50)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox51))
                                .addGroup(arrestTabLayout.createSequentialGroup()
                                    .addComponent(jCheckBox52)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(assaultLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(jCheckBox53)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(assaultandbatteryLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox54)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(assaultdeadlyLEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox55)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox56)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox57)))))
                    .addGroup(arrestTabLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playeridSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offenderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(arrestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(arrestTabLayout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(copytoclipboardButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arrest Calculator", arrestTab);

        javax.swing.GroupLayout ticketTabLayout = new javax.swing.GroupLayout(ticketTab);
        ticketTab.setLayout(ticketTabLayout);
        ticketTabLayout.setHorizontalGroup(
            ticketTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        ticketTabLayout.setVerticalGroup(
            ticketTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ticket Calculator", ticketTab);

        javax.swing.GroupLayout impoundTabLayout = new javax.swing.GroupLayout(impoundTab);
        impoundTab.setLayout(impoundTabLayout);
        impoundTabLayout.setHorizontalGroup(
            impoundTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        impoundTabLayout.setVerticalGroup(
            impoundTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Impound Calculator", impoundTab);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dispatch Organizer", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stats", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Options", jPanel4);

        jScrollPane2.setViewportView(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1076, 928));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(evt.getSource() instanceof javax.swing.JTabbedPane) {
          javax.swing.JTabbedPane pane = (javax.swing.JTabbedPane) evt.getSource();
          if(pane.getSelectedIndex() != 0 && pane.getSelectedIndex() != 4) {
              jDialog1.setEnabled(true);
              jDialog1.show(true);
              pane.setSelectedIndex(0);
          }
          
          switch(pane.getSelectedIndex()) {
              case 4:
                  statsLabel.setText("<html><b>Arrests:</b> "+LVPDProperties.getStat(LVPDProperties.LIFETIME_ARRESTS)+"<br><b>Time:</b> "+LVPDProperties.getStat(LVPDProperties.LIFETIME_TIME)+" minutes<br><b>Fines:</b> $"+LVPDProperties.getStat(LVPDProperties.LIFETIME_FINES)+"<br><b>Strikes:</b> "+LVPDProperties.getStat(LVPDProperties.LIFETIME_STRIKES));
                  jDialog2.setEnabled(true);
                  jDialog2.show(true);
                  pane.setSelectedIndex(0);
          }
       }
    }//GEN-LAST:event_jTabbedPane1StateChanged
    
    //"Close" button in the Beta Dialog
    private void betaDialogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaDialogCloseButtonActionPerformed
        jDialog1.hide();
    }//GEN-LAST:event_betaDialogCloseButtonActionPerformed
    
    //"Copy to Clipboard" button
    private void copytoclipboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copytoclipboardButtonActionPerformed
       if("Copy".equals(evt.getActionCommand())) {
           System.out.println("Hello");
           StringSelection stringSelection = new StringSelection(CalculateAction.CommandString);
           Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
           clipboard.setContents(stringSelection, stringSelection);
       }
    }//GEN-LAST:event_copytoclipboardButtonActionPerformed

    //"Reset" button
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        VariableReset.resetVariables();
    }//GEN-LAST:event_resetButtonActionPerformed
    
    //"Create Criminal Report" button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        URL format = null;
        URL criminalThread = null;
        try { 
            format = new URL("http://www.mt-gaming.com/index.php?threads/new-criminal-report-format.45345/");
        }
        catch(MalformedURLException e){
        }
        try {
            String name = offenderName.getText();
            int idx = 0;
            int count = 0;
            
            for(int i = 0, n = name.length(); i < n; i++) {
                if(name.charAt(i) == ' ') {
                    idx = i;
                    count++;
                }
                if(count == 1){
                    break;
                }
            }
            
            StringBuilder search = new StringBuilder(name);
            search.setCharAt(idx, '+');
            
            criminalThread = new URL("http://mt-gaming.com/index.php/search/search?keywords="+search+"&title_only=1&nodes[]=246");
        }
        catch(MalformedURLException e) {
        }
       
        try { 
            java.awt.Desktop.getDesktop().browse(format.toURI());
            java.awt.Desktop.getDesktop().browse(criminalThread.toURI());
        }
        catch (IOException | URISyntaxException e){
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    //"Calculate" button. Called to outside class file because of how much code it is
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        CalculateAction.actionPerformed(evt);
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void statsDialogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsDialogCloseButtonActionPerformed
        jDialog2.hide();
    }//GEN-LAST:event_statsDialogCloseButtonActionPerformed

    private void statsDialogResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsDialogResetButtonActionPerformed
        LVPDProperties.resetStats();
        statsLabel.setText("<html><b>Arrests:</b> "+LVPDProperties.getStat(LVPDProperties.LIFETIME_ARRESTS)+"<br><b>Time:</b> "+LVPDProperties.getStat(LVPDProperties.LIFETIME_TIME)+" minutes<br><b>Fines:</b> $"+LVPDProperties.getStat(LVPDProperties.LIFETIME_FINES)+"<br><b>Strikes:</b> "+LVPDProperties.getStat(LVPDProperties.LIFETIME_STRIKES));
    }//GEN-LAST:event_statsDialogResetButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try { 
            LVPDProperties.initProperties();
        }
        catch (IOException e) {}
        
        SplashScreen.splashInit();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrestTab;
    public static javax.swing.JRadioButton assaultLEO;
    public static javax.swing.JRadioButton assaultandbatteryLEO;
    public static javax.swing.JRadioButton assaultdeadlyLEO;
    public static javax.swing.JRadioButton attemptedLEO;
    private javax.swing.JButton betaDialogCloseButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton copytoclipboardButton;
    public static javax.swing.JComboBox dischargeComboBox;
    public static javax.swing.JComboBox drugsComboBox;
    public static javax.swing.JTextField drugsTextField;
    public static javax.swing.JRadioButton drugsTraffick;
    public static javax.swing.JRadioButton firearmsTraffick;
    private javax.swing.JLabel heavyLabel;
    private javax.swing.JPanel impoundTab;
    private javax.swing.JButton jButton2;
    public static javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JCheckBox jCheckBox10;
    public static javax.swing.JCheckBox jCheckBox11;
    public static javax.swing.JCheckBox jCheckBox12;
    public static javax.swing.JCheckBox jCheckBox13;
    public static javax.swing.JCheckBox jCheckBox14;
    public static javax.swing.JCheckBox jCheckBox15;
    public static javax.swing.JCheckBox jCheckBox16;
    public static javax.swing.JCheckBox jCheckBox17;
    public static javax.swing.JCheckBox jCheckBox18;
    public static javax.swing.JCheckBox jCheckBox2;
    public static javax.swing.JCheckBox jCheckBox20;
    public static javax.swing.JCheckBox jCheckBox21;
    public static javax.swing.JCheckBox jCheckBox22;
    public static javax.swing.JCheckBox jCheckBox23;
    public static javax.swing.JCheckBox jCheckBox24;
    public static javax.swing.JCheckBox jCheckBox25;
    public static javax.swing.JCheckBox jCheckBox26;
    public static javax.swing.JCheckBox jCheckBox27;
    public static javax.swing.JCheckBox jCheckBox28;
    public static javax.swing.JCheckBox jCheckBox29;
    public static javax.swing.JCheckBox jCheckBox3;
    public static javax.swing.JCheckBox jCheckBox30;
    public static javax.swing.JCheckBox jCheckBox31;
    public static javax.swing.JCheckBox jCheckBox32;
    public static javax.swing.JCheckBox jCheckBox33;
    public static javax.swing.JCheckBox jCheckBox34;
    public static javax.swing.JCheckBox jCheckBox35;
    public static javax.swing.JCheckBox jCheckBox37;
    public static javax.swing.JCheckBox jCheckBox38;
    public static javax.swing.JCheckBox jCheckBox39;
    public static javax.swing.JCheckBox jCheckBox4;
    public static javax.swing.JCheckBox jCheckBox40;
    public static javax.swing.JCheckBox jCheckBox41;
    public static javax.swing.JCheckBox jCheckBox42;
    public static javax.swing.JCheckBox jCheckBox43;
    public static javax.swing.JCheckBox jCheckBox44;
    public static javax.swing.JCheckBox jCheckBox45;
    public static javax.swing.JCheckBox jCheckBox46;
    public static javax.swing.JCheckBox jCheckBox47;
    public static javax.swing.JCheckBox jCheckBox48;
    public static javax.swing.JCheckBox jCheckBox5;
    public static javax.swing.JCheckBox jCheckBox50;
    public static javax.swing.JCheckBox jCheckBox51;
    public static javax.swing.JCheckBox jCheckBox52;
    public static javax.swing.JCheckBox jCheckBox53;
    public static javax.swing.JCheckBox jCheckBox54;
    public static javax.swing.JCheckBox jCheckBox55;
    public static javax.swing.JCheckBox jCheckBox56;
    public static javax.swing.JCheckBox jCheckBox57;
    public static javax.swing.JCheckBox jCheckBox58;
    public static javax.swing.JCheckBox jCheckBox59;
    public static javax.swing.JCheckBox jCheckBox6;
    public static javax.swing.JCheckBox jCheckBox60;
    public static javax.swing.JCheckBox jCheckBox61;
    public static javax.swing.JCheckBox jCheckBox62;
    public static javax.swing.JCheckBox jCheckBox7;
    public static javax.swing.JCheckBox jCheckBox8;
    public static javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextPane jTextPane1;
    public static javax.swing.JRadioButton kidnappingLEO;
    private javax.swing.JLabel lightLabel;
    public static javax.swing.JTextField materialsTextField;
    public static javax.swing.JRadioButton materialsTraffick;
    public static javax.swing.JTextField offenderName;
    public static javax.swing.JSpinner playeridSpinner;
    public static javax.swing.JButton resetButton;
    private javax.swing.JButton statsDialogCloseButton;
    private javax.swing.JButton statsDialogResetButton;
    private javax.swing.JLabel statsLabel;
    public static javax.swing.JRadioButton successfulLEO;
    private javax.swing.JPanel ticketTab;
    private javax.swing.JLabel vehicleLabel;
    public static javax.swing.JComboBox weaponsComboBox;
    // End of variables declaration//GEN-END:variables
}
